#!/usr/bin/env bash
# a script that pings an IP address passed as an argument
# accepts a string as an argument
# displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# pings the IP 5 times

if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
elif [ $# -gt 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
else
	ping "$1" -c 5
fi
