#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid

# Signal handlers
trap 'echo "I hate the kill command";'
trap 'echo "Y U no love me?!";'
trap 'rm -f /var/run/myscript.pid; echo "Terminating..."; exit'

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 1
done
