#!/usr/bin/env bash
# This script is an extension of the previous exercise command and displays line containing the word Bash
# Easily get the PID of the Bash process
# shellcheck disable=SC2009

./1-list_your_processes | grep "[b]ash"
