#!/usr/bin/env bash
# displays a script that stops printing a statement
# Uses the kill command

# Get the PID of the program

id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinte process

if [ -n "$id" ]
then
	kill -15 "$id"
fi
