#!/usr/bin/env bash
# The script displays to infinity and beyond indefinitely
# In between each iteration of the loop, adds a sleep 2
# For every iteration we can see I am invincible!!! when receiving a SIGTERM signal

trap "echo "I am invincible!!!"" 15
while true; do
	echo "To infinity and beyond"
	sleep 2
done
