#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, using the while loop + IFS
# Set the Internal Field Separator to ":"

IFS=":"

# Open the /etc/passwd file and read it line by line

while read -r username password _ gid description home_directory shell; do
  echo "The user $username is part of the $gid gang, lives in $home_directory and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $description"
done < "/etc/passwd"
