#!/usr/bin/env bash
# This script displays "Best School" 10 times using a for loop
# Prints Hi at the 9th time

var="Best School"
var2="Hi"
i="0"

while  [ $i -lt 10 ]; do
  if [ $i -eq 9 ]; then
	  echo "$var2"
  fi
  echo "$var"
  ((i++))
done
